version: "3.9"

services:
  api:
    networks:
      - mailhog

  redis-ui:
    image: marian/rebrow
    networks:
      - redis
    ports:
      - "5001:5001"

  mailhog:
    image: mailhog/mailhog
    networks:
      - mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  mailhog:
