version: '3.5'
services:
  api:
    extends:
      file: conf/docker/docker-compose.base.yml
      service: main_base
    command: ['python', 'manage.py', 'runserver_plus', '0.0.0.0:8000']
    volumes:
      - .:/project/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    extends:
      file: conf/docker/docker-compose.base.yml
      service: postgres

  redis:
    extends:
      file: conf/docker/docker-compose.base.yml
      service: redis

networks:
  postgres:
  redis:

volumes:
  redis_data: