# Generated by Django 4.1.5 on 2023-01-17 14:47

import core.models.mixins.domain_ruler_mixin
import core.models.mixins.entity_mixin
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Provide a name for the app', max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], max_length=10, verbose_name='app type')),
                ('framework', models.CharField(choices=[('django', 'Django'), ('react-native', 'React Native')], max_length=50, verbose_name='framework')),
                ('domain_name', models.CharField(blank=True, help_text='Provide the name of you domain', max_length=50, null=True, verbose_name='domain name')),
                ('screenshot', models.URLField(blank=True, help_text='Provide a URL with an image that shows your application', null=True, verbose_name='screenshot')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['name'],
            },
            bases=(core.models.mixins.entity_mixin.EntityMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Provide a name for the plan', max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['name'],
            },
            bases=(core.models.mixins.entity_mixin.EntityMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('old_plan_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='old plan name')),
                ('current_plan_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='current plan name')),
                ('action_type', models.CharField(choices=[('subscribe', 'Subscribe'), ('switch', 'Switch'), ('unsubscribe', 'Unsubscribe'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], max_length=11, verbose_name='action type')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='old price')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='current price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='applications.application', verbose_name='application')),
            ],
            options={
                'verbose_name': 'subscription history',
                'verbose_name_plural': 'subscription histories',
                'ordering': ['created_at'],
            },
            bases=(core.models.mixins.domain_ruler_mixin.DomainRuleMixin, models.Model),
        ),
        migrations.AddField(
            model_name='application',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='applications.plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
